FROM python:3.12 AS stage

WORKDIR /HalloweenEvent
ENV PYTHONPATH=/HalloweenEvent

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

##########################
# develop
##########################

FROM stage AS dev

ENTRYPOINT ["python3", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "src/api/api.py"]

##########################
# production
##########################

FROM stage AS prod

ENTRYPOINT ["python3", "src/api/api.py"]