services:

  halloween-api-prod:
    container_name: "HalloweenEventApi_prod"
    image: ghcr.io/cgoulart35/halloweenevent-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile.api
      target: prod
    env_file: ./api.env
    volumes:
      - ./serviceAccountKey.json:/HalloweenEvent/serviceAccountKey.json
    restart: unless-stopped
    init: true
    ports:
      - 5007:5004
  halloween-webapp-prod:
    container_name: "HalloweenEventWebApp_prod"
    image: ghcr.io/cgoulart35/halloweenevent-webapp:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile.app
      target: prod
    env_file: ./app.env
    volumes:
      - ./serviceAccountKey.json:/HalloweenEvent/serviceAccountKey.json
    restart: unless-stopped
    init: true
    ports:
      - 5009:5004